
#pragma once

#define TAPPING_TERM 200
#define COMBO_TERM 30
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE

#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
