
#pragma once

#define TAPPING_TERM 200
#define COMBO_TERM 50

#define PERMISSIVE_HOLD_PER_KEY
#define COMBO_TERM_PER_COMBO
#define TAPPING_TERM_PER_KEY
#define COMBO_ONLY_FROM_LAYER 0
#define MOUSEKEY_DELAY 5
#define MOUSEKEY_MAX_SPEED 3
