
#pragma once

#define TAPPING_TERM 173
#define COMBO_TERM 30
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE

#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD